### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by paulomac1000** [imagegenius/docker-esphome#6]
Suggestions to update README.md:

- make sure your user (UID 1000) is in group dialout (mine wasn't by default)
- add docker-compose option `privileged: true` to see all USB
- add `devices: - /dev/ttyUSB0` which is not added by default by above option (USB0 is esp device default name)

**Comment by hydazz** [comment]
> Suggestions to update README.md:
> 
> * make sure your user (UID 1000) is in group dialout (mine wasn't by default)
> * add docker-compose option `privileged: true` to see all USB
> * add `devices: - /dev/ttyUSB0` which is not added by default by above option (USB0 is esp device default name)

mounting devices and passing them through isn't particularly supported, better to just install esphome on the host but I've fixed your first point of incorrect permissions: https://github.com/imagegenius/docker-esphome/commit/a199dbd7dc6f078a239dacc4a6e600e5a0c9a37e - as long as root can access the device the `UID` does not need access to `dialout`
